/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.42.0.0
 *
 * Project: 'AD5940_SqrWaveVoltmmetry' 
 * Target:  'ADICUP3029' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "ADuCM3029.h"



#endif /* RTE_COMPONENTS_H */
